language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t roinel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true roinel/react-test npm test

after_success:
  - docker build -t roinel/multi-client ./client
  - docker build -t roinel/multi-nginx ./nginx
  - docker build -t roinel/multi-server ./server
  - docker build -t roinel/multi-worker ./worker
  # Login to docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push roinel/multi-client
  - docker push roinel/multi-nginx
  - docker push roinel/multi-server
  - docker push roinel/multi-worker
